uname = "<EMAIL HERE>"
pwd = "<PWD HERE>"
email_welcome = """Hello All,
   Welcome message about things! \n \n """
email_reminder = """Hello All, \n
Just a friendly reminder for the {} meetup coming up. Details can be found below and we hope you can make it: \n """
email_close = """\n\n Closing message about stuff and things --- \n Generated by: https://github.com/encima/MeetMail"""
email_rem_close = """<ADIOS HERE>"""
recs_dev = ["<YOUR EMAIL HERE>"]
recs = []
bcc = []
smtp_server = "outlook.office365.com"
smtp_port = 587